### ISSUE TITLE
Question + Thank you

### ISSUE THREAD

**Issue by Robbrt** [pxseu/dotfiles#1]
@pxseu Thanks for the files. Are these up to date and ready to use?

**Comment by pxseu** [comment]
uhhh i will push the changes in a sec, haven't had a chance to do it yesterday

**Comment by Robbrt** [comment]
alright thanks!

**Comment by pxseu** [comment]
after some trouble with gpg should be good to go!

**Comment by Robbrt** [comment]
Perfect!
